AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Boilerplate Using TypeScript

Globals:
  Function:
    Runtime: nodejs16.x # modify the version according to your need
    Timeout: 30

Resources:

  fetchAll:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.fetchAll
      CodeUri: src/lambda-handlers/
      FunctionName: "fetchAll"
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the Users
        - DynamoDBCrudPolicy:
            TableName: !Ref Users
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          TABLE_NAME: !Ref Users
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api
            Method: GET

  findById:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.findById
      CodeUri: src/lambda-handlers/
      FunctionName: "findById"
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by id.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the Users
        - DynamoDBCrudPolicy:
            TableName: !Ref Users
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          TABLE_NAME: !Ref Users
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api/{id}
            Method: GET

  createNew:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.addNew
      CodeUri: src/lambda-handlers/
      FunctionName: "addNew"
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP POST method to add one new item.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the Users
        - DynamoDBCrudPolicy:
            TableName: !Ref Users
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          TABLE_NAME: !Ref Users
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api
            Method: POST
