AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Boilerplate Using TypeScript

Globals:
  Function:
    Runtime: nodejs16.x # modify the version according to your need
    Timeout: 30

Resources:
  ApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      FunctionName: "API-Lambda"
      CodeUri: src/lambda-handlers/
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api
            Method: get
