name: CI run tests step
description: Runs tests and uploads reports

runs:
  using: composite
  steps:
    - name: Node setup
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: NPM install
      shell: bash
      run: npm install

    - name: Run linter
      shell: bash
      run: npm run lint

    - name: Run tests
      shell: bash
      run: npm run coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: Coverage report
        path: coverage/lcov-report/
