name: GitHub Actions CI
run-name: CI triggered by ${{ github.event_name }} event to ${{ github.ref }}
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest # could be some specific release
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        uses: ./.github/workflows/run-tests
